name: spaceship_combat
description: A genetic algorithm breeding spaceship-piloting neural network.
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  darwin: '^0.2.4'
  browser: '>=0.10.0 <0.11.0'
  box2d: '^0.2.0'
  backy: '^0.2.1'
#dev_dependencies:
#  darwin: 
#    path: ../darwin