name: spaceship_combat
description: A sample web application
author: Filip Hracek <filip.hracek@gmail.com>
dependencies:
  darwin: any
  browser: any
  box2d: any
  backy: 0.2.1
#dev_dependencies:
#  darwin: 
#    path: ../darwin